import "./globals.css";
import Header from "../components/global/Header";
// import Footer from "../components/global/Footer";

import { Inter as FontSans } from "next/font/google";

import { cn } from "../lib/utils";
import Footer from "../components/global/Footer";
import { headers } from "next/headers";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const noHeaderFooterPaths = [
  "/auth/login",
  "/auth/signin",
  "/signup",
  "/auth/register",
  "/reset-password",
  "/forgot-password",
  "/checkout",
  "/payment",

  "/404",
  "/500",

  "/admin",
];

export default function RootLayout({ children }) {
  const pathname = headers().get("x-pathname");
  const noHeaderFooter = noHeaderFooterPaths.includes(pathname);

  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-dm-sans antialiased",
          fontSans.variable
        )}
      >
        {!noHeaderFooter && <Header />}

        {children}
        {!noHeaderFooter && <Footer />}
      </body>
    </html>
  );
}
